/**
 * S0.11 — golden-ephemeris verification (vitest, node environment).
 *
 * Re-computes every quantity in tests/golden/ephemeris/ephemeris-golden.json
 * (generated by tools/oracle/generate_golden.py from skyfield 1.55 +
 * de440s.bsp) with astronomy-engine 2.1.19 and measures the residuals.
 *
 * Time handling (the load-bearing convention):
 *  - Geocentric rows: astronomy-engine is evaluated at
 *    `AstroTime.FromTerrestrialTime(fixture.ttDaysSinceJ2000TT)` — the exact
 *    same TT instant skyfield used — so the residual is pure ephemeris-model
 *    difference (astronomy-engine VSOP87/ELP-derived analytic series vs JPL
 *    DE440s) plus the ~0.02 arcsec ICRS<->EQJ frame bias [derived].
 *  - Topocentric rows: evaluated at the same civil UTC instant in both
 *    libraries, so the residual additionally includes a delta-T model term:
 *    Earth rotation (GAST) differs by ~15 arcsec per second of delta-T
 *    disagreement between the two libraries' TT<->UT models [derived].
 *
 * This is the S0.11 measurement backing ADR-011 / ROADMAP §Budgets B-EPH-01.
 * B-CONST-06 (COORDINATE_SYSTEM.md §10): astronomy-engine's stated accuracy is
 * +/-1 arcminute for Solar System bodies [EXTERNAL — astronomy-engine docs];
 * one arcminute subtends ~112 km at the Moon's mean distance [derived].
 *
 * Measured maxima (2026-09-06, 8 dates x 3 geocentric bodies + 2 topocentric):
 * geocentric angular max 0.3454 arcmin (Moon, 2017-08-21); Moon linear max
 * 46.3 km; EMB<->Earth bookkeeping max 0.167 km; topocentric alt/az max
 * 0.093 arcmin. The topocentric residual decomposes into (a) the delta-T
 * model gap — astronomy-engine evaluates positions from a civil Date at
 * TT = UTC + ~75.5 s (Espenak-Meeus 2004 polynomial, DeltaT_EspenakMeeus) vs
 * skyfield's builtin ~69.1 s, a ~6.3 s TT mismatch = ~0.06 arcmin at lunar
 * distance [derived] — and (b) Earth rotation: astronomy-engine's era() uses
 * the civil instant as UT1 while skyfield's builtin timescale puts
 * UT1-UTC = +0.096 s at 2026-09-05, a 1.44 arcsec rotation difference
 * [MEASURED 2026-09-06, GAST comparison at the 2026-09-05 row].
 */
import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import * as Astronomy from 'astronomy-engine';

const FIXTURE_URL = new URL('../../../tests/golden/ephemeris/ephemeris-golden.json', import.meta.url);
const AU_KM = 149597870.7; // exact IAU 2012 definition, matches astronomy-engine's internal constant

// Thresholds are regression pins, not accuracy claims: each sits inside the
// B-CONST-06 stated ~1 arcmin class with headroom above the measured maxima,
// so a changed ephemeris model or broken time adapter fails loudly while the
// measured class does not.
const THRESHOLD_GEOCENTRIC_ARCMIN = 0.5; // measured max 0.3454 (Moon)
const THRESHOLD_MOON_LINEAR_KM = 120; // = 1 arcmin subtension at the Moon's mean distance
const THRESHOLD_EMB_EARTH_LINEAR_KM = 1.0; // measured max 0.167 km on a <= ~5,000 km offset vector
const THRESHOLD_TOPO_ARCMIN = 0.25; // measured max 0.093 (includes the delta-T terms above)

interface Vec3Json {
  x: number;
  y: number;
  z: number;
}

interface FixtureRow {
  isoUtc: string;
  ttJulianDate: number;
  ttDaysSinceJ2000TT: number;
  deltaTSeconds: number;
  geocentricAstrometricICRFkm: Record<'sun' | 'moon' | 'marsBarycenter', Vec3Json>;
  earthBarycentricICRFkm: Vec3Json;
  embBarycentricICRFkm: Vec3Json;
  embToEarthICRFkm: Vec3Json;
  topocentricMoonApparentDarEsSalaam?: { altDeg: number; azDeg: number; distanceKm: number };
}

interface Fixture {
  schema: string;
  oracle: {
    library: string;
    skyfieldVersion: string;
    pythonVersion: string;
    kernel: { file: string; sha256: string; bytes: number; sourceUrl: string; dateRange: string };
    conventions: Record<string, string>;
    site: { latDegKey?: string } & Record<string, unknown>;
    regenerateCommand: string;
  };
  rows: FixtureRow[];
}

function loadFixture(): Fixture {
  return JSON.parse(readFileSync(FIXTURE_URL, 'utf-8')) as Fixture;
}

function vec(a: Vec3Json): [number, number, number] {
  return [a.x, a.y, a.z];
}

function sub(a: [number, number, number], b: [number, number, number]): [number, number, number] {
  return [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
}

function norm(a: [number, number, number]): number {
  return Math.hypot(a[0], a[1], a[2]);
}

/** Angular separation between two 3-D directions, rad (atan2 form, f64-stable). */
function angleBetween(a: [number, number, number], b: [number, number, number]): number {
  const dot = a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
  const cross: [number, number, number] = [
    a[1] * b[2] - a[2] * b[1],
    a[2] * b[0] - a[0] * b[2],
    a[0] * b[1] - a[1] * b[0],
  ];
  return Math.atan2(norm(cross), dot);
}

/** Unit vector from alt/az degrees (alt above horizon, az clockwise from north). */
function altAzToUnit(altDeg: number, azDeg: number): [number, number, number] {
  const alt = (altDeg * Math.PI) / 180;
  const az = (azDeg * Math.PI) / 180;
  const ca = Math.cos(alt);
  return [ca * Math.cos(az), ca * Math.sin(az), Math.sin(alt)];
}

const ARCMIN_PER_RAD = (180 / Math.PI) * 60;
const radToArcmin = (rad: number): number => (rad * ARCMIN_PER_RAD);

describe('S0.11: golden ephemeris — astronomy-engine vs skyfield/de440s fixtures', () => {
  const fixture = loadFixture();
  const measured = {
    fixtureSha256Kernel: fixture.oracle.kernel.sha256,
    skyfieldVersion: fixture.oracle.skyfieldVersion,
    rows: fixture.rows.length,
    geocentricArcmin: {} as Record<string, number>,
    geocentricLinearKm: {} as Record<string, number>,
    maxGeocentricArcmin: 0,
    maxGeocentricArcminAt: '',
    maxMoonLinearKm: 0,
    embEarthLinearKm: {} as Record<string, number>,
    maxEmbEarthLinearKm: 0,
    topoArcmin: {} as Record<string, number>,
    maxTopoArcmin: 0,
    maxTopoArcminAt: '',
    deltaTModelMaxDisagreementSeconds: 0,
  };

  it('fixture carries the pinned oracle contract', () => {
    expect(fixture.schema).toBe('kwetu.golden.ephemeris/1');
    expect(fixture.oracle.library).toBe('skyfield');
    expect(fixture.oracle.kernel.file).toBe('de440s.bsp');
    expect(fixture.oracle.kernel.sha256).toBe(
      'c1c7feeab882263fc493a9d5a5b2ddd71b54826cdf65d8d17a76126b260a49f2',
    );
    expect(fixture.oracle.conventions.frame).toContain('ICRF');
    expect(fixture.rows.length).toBe(8);
    expect(fixture.rows.map((r) => r.isoUtc)).toContain('2026-09-05T00:00:00Z');
  });

  it('geocentric astrometric positions agree inside the stated ~1 arcmin class', () => {
    for (const row of fixture.rows) {
      // The fixture records the TT instant in BOTH conventions (skyfield's
      // t.tt is a full TT Julian Date; astronomy-engine's TT is days since
      // J2000 TT = JD 2451545.0). Pin the mapping, then evaluate at the
      // identical TT instant as the oracle (see header).
      expect(row.ttDaysSinceJ2000TT).toBeCloseTo(row.ttJulianDate - 2451545.0, 9);
      const time = Astronomy.AstroTime.FromTerrestrialTime(row.ttDaysSinceJ2000TT);
      const bodies = {
        sun: Astronomy.Body.Sun,
        moon: Astronomy.Body.Moon,
        marsBarycenter: Astronomy.Body.Mars,
      } as const;
      for (const key of ['sun', 'moon', 'marsBarycenter'] as const) {
        const gv = Astronomy.GeoVector(bodies[key], time, false); // EQJ AU, light-time, no aberration
        const oursKm: [number, number, number] = [gv.x * AU_KM, gv.y * AU_KM, gv.z * AU_KM];
        const goldenKm = vec(row.geocentricAstrometricICRFkm[key]);
        const angularArcmin = radToArcmin(angleBetween(oursKm, goldenKm));
        const linearKm = norm(sub(oursKm, goldenKm));
        measured.geocentricArcmin[`${row.isoUtc} ${key}`] = angularArcmin;
        measured.geocentricLinearKm[`${row.isoUtc} ${key}`] = linearKm;
        if (angularArcmin > measured.maxGeocentricArcmin) {
          measured.maxGeocentricArcmin = angularArcmin;
          measured.maxGeocentricArcminAt = `${row.isoUtc} ${key}`;
        }
        if (key === 'moon' && linearKm > measured.maxMoonLinearKm) {
          measured.maxMoonLinearKm = linearKm;
        }
        expect(angularArcmin).toBeLessThan(THRESHOLD_GEOCENTRIC_ARCMIN);
        if (key === 'moon') {
          expect(linearKm).toBeLessThan(THRESHOLD_MOON_LINEAR_KM);
        }
      }
    }
  });

  it('EMB -> Earth bookkeeping offset agrees to the measured class', () => {
    for (const row of fixture.rows) {
      const time = Astronomy.AstroTime.FromTerrestrialTime(row.ttDaysSinceJ2000TT);
      const earth = Astronomy.HelioVector(Astronomy.Body.Earth, time);
      const emb = Astronomy.HelioVector(Astronomy.Body.EMB, time);
      const oursKm: [number, number, number] = [
        (earth.x - emb.x) * AU_KM,
        (earth.y - emb.y) * AU_KM,
        (earth.z - emb.z) * AU_KM,
      ];
      const goldenKm = vec(row.embToEarthICRFkm);
      const linearKm = norm(sub(oursKm, goldenKm));
      measured.embEarthLinearKm[row.isoUtc] = linearKm;
      measured.maxEmbEarthLinearKm = Math.max(measured.maxEmbEarthLinearKm, linearKm);
      expect(linearKm).toBeLessThan(THRESHOLD_EMB_EARTH_LINEAR_KM);
      // The offset vector itself is a few thousand km — sanity, not tolerance.
      expect(norm(goldenKm)).toBeGreaterThan(0);
    }
  });

  it('topocentric Moon alt/az (Dar es Salaam) agrees inside the combined ephemeris + delta-T class', () => {
    for (const row of fixture.rows) {
      const topo = row.topocentricMoonApparentDarEsSalaam;
      if (!topo) continue;
      // Same civil UTC instant in both libraries (see header re: delta-T term).
      const when = new Date(row.isoUtc);
      const observer = new Astronomy.Observer(-6.79, 39.21, 0);
      const eq = Astronomy.Equator(Astronomy.Body.Moon, when, observer, true, true);
      const hor = Astronomy.Horizon(when, observer, eq.ra, eq.dec); // no refraction
      const angularArcmin = radToArcmin(
        angleBetween(altAzToUnit(hor.altitude, hor.azimuth), altAzToUnit(topo.altDeg, topo.azDeg)),
      );
      measured.topoArcmin[row.isoUtc] = angularArcmin;
      if (angularArcmin > measured.maxTopoArcmin) {
        measured.maxTopoArcmin = angularArcmin;
        measured.maxTopoArcminAt = row.isoUtc;
      }
      // delta-T model disagreement (seconds) between the libraries at this
      // instant: DeltaT_EspenakMeeus returns seconds and overshoots skyfield's
      // builtin delta-T by ~6.3 s at 2026 (see header) — this is the ~0.06
      // arcmin TT-mismatch term inside the measured topocentric residual.
      const aeDeltaT = Astronomy.DeltaT_EspenakMeeus(new Astronomy.AstroTime(when).ut);
      measured.deltaTModelMaxDisagreementSeconds = Math.max(
        measured.deltaTModelMaxDisagreementSeconds,
        Math.abs(aeDeltaT - row.deltaTSeconds),
      );
      expect(angularArcmin).toBeLessThan(THRESHOLD_TOPO_ARCMIN);
    }
  });

  it('records the measured maxima (the real B-EPH-01 values) in this run log', () => {
    // Not a tolerance — a report hook: the numbers land in
    // tools/spikes/s0.11/report.json and ADR-011 §Evidence.
    console.log('[B-EPH-01 measured]', JSON.stringify(measured, null, 2));
    expect(measured.maxGeocentricArcmin).toBeGreaterThan(0); // a real measurement happened
  });
});
