# Basemap bake — per-region PMTiles via planetiler (OpenMapTiles profile).
#
# Regeneration path for the L1 vector basemap (ROADMAP §3.2, B-LOAD/B-BAKE rows;
# provenance rules in DATA_SOURCES.md). Output is an OSM-derived database:
# it lives in .bake/ (gitignored) and is regenerated by this pinned script,
# never committed. Attribution obligations of the output: STR-OSM joined with
# STR-OMT (ATTRIBUTIONS.md) — the OpenMapTiles schema requires a visible credit.
#
# Pin: planetiler image digest recorded in THIRD_PARTY_ASSETS.md code-08
# (re-pin deliberately on refresh — do not silently float :latest).
#
# Source: Geofabrik Tanzania extract (download.geofabrik.de/africa/tanzania-latest.osm.pbf,
# recorded timestamp: the file fetched 2026-09-06 for the first bake — record the
# fresh date on any re-download; *.osm.pbf is gitignored).
#
# Usage:  pwsh tools/bake/basemap.ps1 [-Pbf <path-to-osm.pbf>] [-Bounds "W,S,E,N"] [-Out dar-zanzibar.pmtiles]
param(
    [string]$Pbf = ".bake/incoming/tanzania-latest.osm.pbf",
    [string]$Bounds = "38.95,-7.05,39.6,-5.75",
    [string]$Out = "dar-zanzibar.pmtiles"
)

$ErrorActionPreference = "Stop"
$pbfFull = (Resolve-Path $Pbf).Path
New-Item -ItemType Directory -Force .bake/pmtiles | Out-Null

# First bake (2026-09-06): --bounds "38.95,-7.05,39.6,-5.75" (Dar es Salaam +
# Zanzibar channel + Zanzibar island), --maxzoom 15, aux sources downloaded
# (lake centerlines, water polygons, Natural Earth) per the OMT profile.
# Wall time [MEASURED 2026-09-06, dev box]: 20 min 43 s, output 63,203,540 B.
docker run --rm `
    -v "$pbfFull:/data/in/input.osm.pbf" `
    -v "${PWD}/.bake/pmtiles:/data/pmtiles" `
    -v "${PWD}/.bake/sources:/data/data/sources" `
    -e JAVA_TOOL_OPTIONS="-Xmx5g" `
    ghcr.io/onthegomap/planetiler@sha256:db66b104ad08a7cde33ebbb9f371ab0ed2dbe62dc1daeb7a5179709257595e54 `
    --osm_path=/data/in/input.osm.pbf `
    --bounds=$Bounds `
    --maxzoom=15 `
    --download `
    --output=/data/pmtiles/$Out

Write-Host ""
Write-Host "Baked .bake/pmtiles/$Out — serve over HTTP with CORS + range requests"
Write-Host "(Caddy; ARCHITECTURE.md data plane). Attribution: STR-OSM + STR-OMT."
